USE AmazonDB;

-- 1)List all customers who have made purchases of more than $80.
SELECT product_id, customer_name, price, category, stock
FROM Products
WHERE price > 80;

-- 2)Retrieve all orders placed in the last 280 days along with the customer name and email.
SELECT Users.user_name, Users.email, Orders.user_id, Orders.order_date, Orders.total_amount
FROM Orders
INNER JOIN Users ON Orders.user_id = Users.user_id
WHERE Orders.order_date >= CURRENT_DATE - INTERVAL 280 DAY;

-- 3)Find the average product price for each category.
SELECT category,
    AVG(price) AS average_price
FROM Products
GROUP BY category;

-- 4)List all customers who have purchased a product from the category Electronics
SELECT DISTINCT Users.user_name, Users.email
FROM Users
INNER JOIN Orders ON Users.user_id = Orders.user_id
INNER JOIN OrderDetails ON Orders.order_id = OrderDetails.order_id
INNER JOIN Products ON OrderDetails.product_id = Products.product_id
WHERE Products.category = 'Electronics';

-- 5)Find the total number of products sold and the total revenue generated for each product.
SELECT Products.product_id, Products.product_name, 
    SUM(OrderDetails.quantity) AS products_sold,
    SUM(OrderDetails.quantity * Products.price) AS total_revenue
FROM Products
INNER JOIN OrderDetails ON Products.product_id = OrderDetails.product_id
GROUP BY Products.product_id, Products.product_name;

-- 6)Update the price of all products in the Books category, increasing it by 10%. Query. 
SET SQL_SAFE_UPDATES = 0;
UPDATE Products
SET price = price * 1.10
WHERE category = 'Books';

-- 7)Remove all orders that were placed before 2020.
DELETE FROM Orders
WHERE order_date < '2020-01-01';

-- 8)Write a query to fetch the order details, including customer name, product name, and quantity, for orders placed on 2024-05-01.
SELECT Users.user_name, Products.product_name, OrderDetails.quantity
FROM OrderDetails
INNER JOIN Orders ON OrderDetails.order_id = Orders.order_id
INNER JOIN Users ON Orders.user_id = Users.user_id
INNER JOIN Products ON OrderDetails.product_id = Products.product_id
WHERE Orders.order_date = '2024-05-01';

-- 9)Fetch all customers and the total number of orders they have placed.
SELECT Users.user_id, Users.user_name, 
	   COUNT(Orders.order_id) AS total_orders
FROM Users
LEFT JOIN Orders ON Users.user_id = Orders.user_id
GROUP BY Users.user_id, Users.user_name;

-- 10)Retrieve the average rating for all products in the Electronics category. (NO RATING COLUMNS IN DATABASE)
-- 11)List all customers who purchased more than 1 units of any product, including the product name and total quantity purchased.
SELECT Users.user_name, Products.product_name,
       SUM(OrderDetails.quantity) AS total_quantity
FROM Users
INNER JOIN Orders ON Users.user_id = Orders.user_id
INNER JOIN OrderDetails ON Orders.order_id = OrderDetails.order_id
INNER JOIN Products ON OrderDetails.product_id = Products.product_id
GROUP BY Users.user_name, Products.product_name
HAVING SUM(OrderDetails.quantity) > 1;

-- 12)Find the total revenue generated by each category along with the category name.
SELECT Products.category,
       SUM(OrderDetails.quantity * Products.price) AS total_revenue
FROM Products
INNER JOIN OrderDetails ON Products.product_id = OrderDetails.product_id
GROUP BY Products.category;